//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_CSharp.ServiceReferenceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsuario.wsLoginSoap")]
    public interface wsLoginSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _Usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Cliente_CSharp.ServiceReferenceUsuario.LoginResponse Login(Cliente_CSharp.ServiceReferenceUsuario.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_CSharp.ServiceReferenceUsuario.LoginResponse> LoginAsync(Cliente_CSharp.ServiceReferenceUsuario.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_CSharp.ServiceReferenceUsuario.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Cliente_CSharp.ServiceReferenceUsuario.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _Contraseña;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string _Usuario, string _Contraseña) {
            this._Usuario = _Usuario;
            this._Contraseña = _Contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_CSharp.ServiceReferenceUsuario.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Cliente_CSharp.ServiceReferenceUsuario.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_CSharp.ServiceReferenceUsuario.ArrayOfString LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(Cliente_CSharp.ServiceReferenceUsuario.ArrayOfString LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsLoginSoapChannel : Cliente_CSharp.ServiceReferenceUsuario.wsLoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsLoginSoapClient : System.ServiceModel.ClientBase<Cliente_CSharp.ServiceReferenceUsuario.wsLoginSoap>, Cliente_CSharp.ServiceReferenceUsuario.wsLoginSoap {
        
        public wsLoginSoapClient() {
        }
        
        public wsLoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsLoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_CSharp.ServiceReferenceUsuario.LoginResponse Cliente_CSharp.ServiceReferenceUsuario.wsLoginSoap.Login(Cliente_CSharp.ServiceReferenceUsuario.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public Cliente_CSharp.ServiceReferenceUsuario.ArrayOfString Login(string _Usuario, string _Contraseña) {
            Cliente_CSharp.ServiceReferenceUsuario.LoginRequest inValue = new Cliente_CSharp.ServiceReferenceUsuario.LoginRequest();
            inValue.Body = new Cliente_CSharp.ServiceReferenceUsuario.LoginRequestBody();
            inValue.Body._Usuario = _Usuario;
            inValue.Body._Contraseña = _Contraseña;
            Cliente_CSharp.ServiceReferenceUsuario.LoginResponse retVal = ((Cliente_CSharp.ServiceReferenceUsuario.wsLoginSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_CSharp.ServiceReferenceUsuario.LoginResponse> Cliente_CSharp.ServiceReferenceUsuario.wsLoginSoap.LoginAsync(Cliente_CSharp.ServiceReferenceUsuario.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_CSharp.ServiceReferenceUsuario.LoginResponse> LoginAsync(string _Usuario, string _Contraseña) {
            Cliente_CSharp.ServiceReferenceUsuario.LoginRequest inValue = new Cliente_CSharp.ServiceReferenceUsuario.LoginRequest();
            inValue.Body = new Cliente_CSharp.ServiceReferenceUsuario.LoginRequestBody();
            inValue.Body._Usuario = _Usuario;
            inValue.Body._Contraseña = _Contraseña;
            return ((Cliente_CSharp.ServiceReferenceUsuario.wsLoginSoap)(this)).LoginAsync(inValue);
        }
    }
}
